language: objective-c
os:
- osx
before_install:
# Get build dependencies
- brew install cmake
- brew install wget
- brew install https://raw.github.com/eugeneoden/homebrew/eca9de1/Library/Formula/sshpass.rb
- if [ "$CXX" == "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
install:
- mkdir $TRAVIS_BUILD_DIR/build
- cd $TRAVIS_BUILD_DIR/build
# Create unix makefiles
- cmake -DCMAKE_BUILD_TYPE=Release ../
before_script:
# Don't ask for confirmation when using scp
- echo -e "Host frs.sourceforge.net\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- wget --quiet --continue https://www.dropbox.com/s/fw4mrhzo733xtdm/caesaria_latest_resources.zip
- PACK_DIR=$TRAVIS_BUILD_DIR/../caesaria-r
- mkdir $PACK_DIR
- unzip -n caesaria_latest_resources.zip -d $PACK_DIR
- cp $PACK_DIR/resources/gfx/* $TRAVIS_BUILD_DIR/bin/resources/gfx  
script:
# Build CaesarIA
- cd $TRAVIS_BUILD_DIR/build
- make -j4
after_success:
- cd $TRAVIS_BUILD_DIR/bin
# Prepare ZIP archive
- rm resources/settings.model
- echo "{ oldgfx:1 } >> resources/settings.model
- ZIPNAME=caesaria-0.5-macos-c3-`date +"%Y%m%d"`.zip
- echo Compress to $ZIPNAME
- zip -r $ZIPNAME *
- chmod 666 $ZIPNAME
# Upload to server
- sshpass -p "$SCP_PASS" scp -v $ZIPNAME dalerank@frs.sourceforge.net:/home/frs/project/opencaesar3/bin/
- sshpass -p "$SCP_PASS" scp -v *.macos dalerank@frs.sourceforge.net:/home/frs/project/opencaesar3/stuff/
env:
notifications:
    slack:
        - caesariagame:m3lwdYPWqeCOn0zWs0rjX5KY
    irc:
        - "irc.quakenet.org#caesaria"
    on_failure: always
    on_success: always
