language: cpp
compiler: gcc
branches:
- windows-build
before_install:
# Get build dependencies
- sudo add-apt-repository --yes ppa:ubuntu-wine/ppa
- sudo apt-get -qq update
- sudo apt-get -qq install cmake p7zip-full build-essential libasound2-dev 
- sudo apt-get -qq install gcc-mingw-w64-i686 g++-mingw-w64-i686 binutils-mingw-w64-i686 mingw-w64-dev wine1.7
- export CMAKE_C_COMPILER=i686-w64-mingw32-gcc
- export CMAKE_CXX_COMPILER=i686-w64-mingw32-g++
install:
- mkdir $TRAVIS_BUILD_DIR/build
- cd $TRAVIS_BUILD_DIR/build
# Create unix makefiles
- cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=xcompile/win32-cross.cmake ../
before_script:
# Don't ask for confirmation when using scp
- echo -e "Host frs.sourceforge.net\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- wget --quiet --continue https://www.dropbox.com/s/fw4mrhzo733xtdm/caesaria_latest_resources.zip
- PACK_DIR=$TRAVIS_BUILD_DIR/../caesaria-r
- mkdir $PACK_DIR
- unzip -n caesaria_latest_resources.zip -d $PACK_DIR
script:
# Build CaesarIA
- cd $TRAVIS_BUILD_DIR/build
- make -j4
after_success:
- cd $TRAVIS_BUILD_DIR/bin
# Prepare ZIP archive
- rm resources/settings.model
- echo "{ oldgfx:1 } >> resources/settings.model
- ZIPNAME=caesaria-0.5-win32-c3-$TRAVIS_BRANCH-`date +"%Y%m%d"`.zip
- echo "Compress to $ZIPNAME"
- zip -r $ZIPNAME *
- chmod 666 $ZIPNAME
# Upload to server
- sshpass -p "$SCP_PASS" scp -v $ZIPNAME dalerank@frs.sourceforge.net:/home/frs/project/opencaesar3/bin/
- sshpass -p "$SCP_PASS" scp -v *.exe dalerank@frs.sourceforge.net:/home/frs/project/opencaesar3/stuff/
env:
notifications:
    slack:
        - caesariagame:m3lwdYPWqeCOn0zWs0rjX5KY
    irc:
        - "irc.quakenet.org#caesaria"
    on_failure: always
    on_success: always
