language: cpp
compiler:
- clang
- gcc
before_install:
# Get build dependencies
- sudo apt-add-repository --yes ppa:zoogie/sdl2-snapshots #libsdl2
- sudo apt-get -qq update
#- sudo apt-get install -qq --force-yes libgd2-xpm ia32-libs ia32-libs-multiarch
- sudo apt-get install -qq cmake build-essential libasound2-dev
#- sudo apt-get install -qq gcc-multilib g++-multilib
install:
# Create unix makefiles
- cmake -DCMAKE_BUILD_TYPE=Release .
script:
# Build CaesarIA
- make -j4
notifications:
    slack:
        - caesariagame:m3lwdYPWqeCOn0zWs0rjX5KY
    on_failure: always
    on_success: never
